var json = {
    "Elements": [{
            "name": "Hydrogen",
            "symbol": "H",
            "atomic_number": 1,
            "atomic_weight": 1.0079,
            "electron_configuration": "1s1",
            "category": "diatomic nonmetal",
            "form": "Gas",
            "source": "",
            "isotopes": "Deuterium,Tritium",
            "wiki_link": "https://en.wikipedia.org/wiki/Hydrogen",
            "compound": [{
                "water": "2H2O",
                "sulfuricacid": "H2SO4",
                "chloride": "Cl-",
                "Hydroxide": "OH-"
            }],
            "extrainfo": {
                "History": "Gr. hydro water and genes forming Hydrogen was prepared many years before it was recognized as a distinct substance by Cavendish in 1776 Named by Lavoisier hydrogen is the most abundant of all elements in the universe.The heavier elementswere originally made from Hydrogen or from other elements that were originally made from Hydrogen.",

                "Uses": "Great quantities are required commercially for the fixation of nitrogen from the air in the Haber ammonia process and for the hydrogenation of fats and oils. It is also used in large quantities in methanol production, in hydrodealkylation, hydrocracking, and hydrodesulfurization. Other uses include rocket fuel welding producing hydrochloric acid reducing metallic ores and filling balloons.The lifting power of 1 cubic foot of hydrogen gas is about 0.07 lb at 0C760 mm pressure.The Hydrogen Fuel cell is a developing technology that will allow great amounts of electrical power tobe obtained using a source of hyrogen gas.Consideration is being given to an entire economy based on solar- and nuclear-generated hydrogen.Public acceptance high capital investment and the high cost of hydrogen with respect to today's fuels are but a few of the problems facing such an economy. Located in remote regions, power plants wouldelectrolyze seawater the hydrogen produced would travel to distant cities by pipelines. Pollution-freehydrogen could replace natural gas gasoline etc and could serve as a reducing agent in metallurgychemical processing refining etc It could also be used to convert trash into methane and ethylene.",

                "Forms": "Quite apart from isotopes it has been shown that under ordinary conditions hydrogen gas is a mixture of two kinds of molecules known as ortho- and para-hydrogen which differ from one another by the spins of their electrons and nuclei Normal hydrogen at room temperature contains 25% of the para form and 75% of the ortho form Theortho form cannot be prepared in the pure state Since the two forms differ in energy the physical properties also differ The melting and boiling points of parahydrogen are about 0.1oC lower than those of normal hydrogen",

                "Isotopes": "The ordinary isotope of hydrogen H is known as Protium the other two isotopes are Deuterium a proton and a neutro and Tritium a protron and two neutrons Hydrogen is the only element whose isotopes have been given different names Deuterium and Tritium are both used as fuel in nuclear fusion reactors One atom of Deuterium is found in about 6000 ordinary hydrogen atoms Deuterium is used as a moderator to slow down neutrons Tritium atoms are also present but in much smaller proportions Tritium is readily produced in nuclear reactors and is used in the production of thehydrogen fusion bomb It is also used as a radioactive agent in making luminous paints and as atracer "
            }
        },
        {
            "name": "Helium",
            "symbol": "He",
            "atomic_number": 2,
            "atomic_weight": 4.00260,
            "electron_configuration": "1s2",
            "source": "hydrogen",
            "form": "gas",
            "category": "noblegas",
            "isotopes": "liquid helium",
            "wiki_link": "https://en.wikipedia.org/wiki/Helium",
            "compound": [
                null
            ],
            "extrainfo": {
                "History": "Gr helios the sun Janssen obtained the first evidence of helium during the solar eclipse of 1868 when he detected a new line in the solar spectrum Lockyer and Frankland suggested the name helium for the new element In 1895 Ramsay discovered helium in the uranium mineral clevite while it was independently discovered in cleveite by the Swedish chemists Cleve and Langlet at about the same time Rutherford and Royds in 1907 demonstrated that alpha particles are helium nuclei",

                "Cost": "The cost of helium fell from $2500/ft3 in 1915 to 1.5 cents /ft3 in 1940 The U.S. Bureau of Mines has setthe price of Grade A helium at $37.50/1000 ft3 in 1986 Materials which become super conductive at higher temperatures than the boiling point of helium couldhave a major impact on the demand for helium These less costly refrigerant materials could replace thepresent need to cool superconductive materials to the boiling point of helium.",

                "Isotopes": "Seven isotopes of helium are known Liquid helium (He4) exists in two forms: He4I and He4II with a sharp transition point at 2.174K He4I (above this temperature) is a normal liquid but He4II (below it) is unlike any other known substance It expands on cooling its conductivity for heat is enormous and neither its heat conduction nor viscosity obeys normal rules",

                "Uses": "as an inert gas shield for arc welding a protective gas in growing silicon and germanium crystals and producing titanium and zirconium as a cooling medium for nuclear reactors and as a gas for supersonic wind tunnels A mixture of helium and oxygen is used as an artificial atmosphere for divers and others working under pressure Different ratios of He/O2 are used for different depths at which the diver is operating Helium is extensively used for filling balloons as it is a much safer gas than hydrogen. One of the recent largest uses for helium has been for pressuring liquid fuel rockets. A Saturn booster like the type used on the Apollo lunar missions required about 13 million ft3 of helium for a firing plus more for checkouts Liquid helium's use in magnetic resonance imaging (MRI) continues to increase as the medical profession accepts and develops new uses for the equipment This equipment has eliminated some need for exploratory surgery by accurately diagnosing patients Another medical application uses MRE t Helium determine (by blood analysis) whether a patient has any form of cancer Helium is also being used to advertise on blimps for various companies including Goodyear Other lifting gas applications are being developed by the Navy and Air Force to detect low-flying cruise missiles Additionally the Drug Enforcement Agency is using radar-equipped blimps to detect drug smugglers along the United States boarders. In addition, NASA is currently using helium-filled balloons to sample the atmosphere in Antarctica to determine what is depleting the ozone layer."
            }
        },
        {
            "name": "Lithium",
            "atomic_number": 3,
            "symbol": "Li",
            "atomic_weight": 6.941,
            "electron_configuration": "[He]2s1",
            "category": "alkali metal",
            "form": "solid",
            "source": "none",
            "isotopes": "none",
            "wiki_link": "https://en.wikipedia.org/wiki/Lithium",
            "compound": [
                null
            ],
            "extrainfo": {
                "History": "(Gr. lithos, stone) Discovered by Arfvedson in 1817. Lithium is the lightest of all metals, with a density only about half that of water",

                "Uses": "Since World War II, the production of lithium metal and its compounds has increased greatly. Because the metal has the highest specific heat of any solid element, it has found use in heat transfer applications; however, it is corrosive and requires special handling. The metal has been used as an alloying agent, is of interest in synthesis of organic compounds, and has nuclear applications. It ranks as a leading contender as a battery anode material as it has a high electrochemical potential. Lithium is used in special glasses and ceramics. The glass for the 200-inch telescope at Mt. Palomar contains lithium as a minor ingredient.Lithium chloride is one of the most lyproscopic materials known, and it, as well as lithium bromide, isused in air conditioning and industrial drying systems. Lithium stearate is used as an all-purpose and high-temperature lubricant. Other lithium compounds are used in dry cells and storage batteries.",

                "Cost": "The metal is priced at about $300/lb"
            }
        },
        {
            "name": "Beryllium",
            "atomic_number": "4",
            "atomic_weight": "9.01218",
            "symbol": "Be",
            "electron_configuration": "[He]2s2",
            "isotopes": "none",
            "form": "solid",
            "category": "alkaline earth metal",
            "source": "none",
            "wiki_link": "https://en.wikipedia.org/wiki/Beryllium",
            "compound": [
                null
            ],
            "extrainfo": {
                "History": "(Gr. beryllos, beryl; also called Glucinium or Glucinum, Gr. glykys, sweet) Discovered as the oxide by Vauquelin in beryl and in emeralds in 1798. The metal was isolated in 1828 by Wohler and by Bussy independently by the action of potassium on beryllium chloride.",

                "Uses": "Beryllium is used as an alloying agent in producing beryllium copper, which is extensively used for springs, electrical contacts, spot-welding electrodes, and non-sparking tools. It is applied as a structural material for high-speed aircraft, missiles, spacecraft, and communication satellites. Other uses include windshield frame, brake discs, support beams, and other structural components of the space shuttle. Because beryllium is relatively transparent to X-rays, ultra-thin Be-foil is finding use in X-ray lithography for reproduction of micro-miniature integrated circuits. Beryllium is used in nuclear reactors as a reflector or moderator for it has a low thermal neutron absorption cross section. It is used in gyroscopes, computer parts, and instruments where lightness, stiffness, and dimensional stability are required. The oxide has a very high melting point and is also used in nuclear work and ceramic applications."
            }
        },
        {
            "name": "Boron",
            "atomic_number": "5",
            "atomic_weight": "10.81",
            "symbol": "B",
            "electron_configuration": "[He]2s2 2p1",
            "isotopes": "none",
            "form": "solid",
            "category": "metalloid",
            "source": "none",
            "wiki_link": "https://en.wikipedia.org/wiki/Boron",
            "compound": [
                null
            ],
            "extrainfo": {
                "History": "(Ar. Buraq, Pers. Burah) Boron compounds have been known for thousands of years, but the element was not discovered until 1808 by Sir Humphry Davy and by Gay-Lussac and Thenard.",

                "Uses": "Amorphous boron is used in pyrotechnic flares to provide a distinctive green color, and in rockets as an igniter. By far the most commercially important boron compound in terms of dollar sales is Na2B4O7.5H2O. This pentahydrate is used in very large quantities in the manufacture of insulation fiberglass and sodium perborate bleach. Boric acid is also an important boron compound with major markets in textile products. Use of borax as a mild antiseptic is minor in terms of dollars and tons. Boron compounds are also extensively used in the manufacture of borosilicate glasses. Other boron compounds show promise in treating arthritis. The isotope boron-10 is used as a control for nuclear reactors, as a shield for nuclear radiation, and in instruments used for detecting neutrons. Boron nitride has remarkable properties and can be used to make a material as hard as diamond. The nitride also behaves like an electrical insulator but conducts heat like a metal. It also has lubricating properties similar to graphite. The hydrides are easily oxidized with considerable energy liberation, and have been studied for use as rocket fuels. Demand is increasing for boron filaments, a high-strength, lightweight material chiefly employed for advanced aerospace structures. Boron is similar to carbon in that it has a capacity to form stable covalently bonded molecular networks. Carbonates, metalloboranes, phosphacarboranes, and other families comprise thousands of compounds.",

                "Cost": "Crystalline boron (99%) costs about $5/g. Amorphous boron costs about $2/g"
            }
        },
        {
            "name": "Carbon",
            "atomic_number": "6",
            "atomic_weight": "12.011",
            "symbol": "C",
            "electron_configuration": "[He]2s2 2p2",
            "isotopes": "none",
            "form": "solid",
            "category": "polyatomic nonmetal",
            "source": "none",
            "wiki_link": "https://en.wikipedia.org/wiki/Carbon",
            "compound": [{
                "carbon_dioxide": "(CO2)",
                "carbon_monoxide": "(CO)",
                "carbon_disulfide": "(CS2)",
                "chloroform ": "(CHCl3)",
                "carbon_tetrachloride": "(CCl4)",
                "methane": "(CH4)",
                "ethylene": "(C2H4)",
                "acetylene": "(C2H2)",
                "benzene": "(C6H6)",
                "acetic_acid": "(CH3COOH)"
            }],
            "extrainfo": {
                "History": "(Latin: carbo, charcoal) Carbon, an element of prehistoric discovery, is very widely distributed in nature.It is found in abundance in the sun, stars, comets, and atmospheres of most planets. Carbon in the form of microscopic diamonds is found in some meteorites. Natural diamonds are found in kimberlite of ancient volcanic 'pipes' found in South Africa, Arkansas,and elsewhere. Diamonds are now also being recovered from the ocean floor off the Cape of Good Hope.About 30% of all industrial diamonds used in the U.S. are now made synthetically.The energy of the sun and stars can be attributed at least in part to the well-known carbon-nitrogen cycle.",

                "Costs": "As of 1990 carbon-13 was commercially available at a cost of about $700/g"
            }
        },
        {
            "name": "Nitrogen",
            "atomic_number": "7",
            "atomic_weight": "14.00674",
            "symbol": "N",
            "electron_configuration": "[He]2s2 2p3",
            "isotopes": "none",
            "form": "gas",
            "category": "diatomic nonmetal",
            "source": "none",
            "wiki_link": "https://en.wikipedia.org/wiki/Nitrogen",
            "compound": [{
                "Sodium_nitrate": "(NaNO3)",
                "potassium_nitrate": "(KNO3)",
                "Ammonia": "(NH3)"
            }],
            "extrainfo": {
                "History": "(L. nitrum, Gr. Nitron, native soda; genes, forming) Nitrogen was discovered by chemist and physician Daniel Rutherford in 1772. He removed oxygen and carbon dioxide from air and showed that the residual gas would not support combustion or living organisms. At the same time there were other noted scientists working on the problem of nitrogen. These included Scheele,Cavendish, Priestley, and others. They called it burnt or dephlogisticated air which meant air without oxygen."
            }
        },
        {
            "name": "Oxygen",
            "atomic_number": "8",
            "atomic_weight": "15.9994",
            "symbol": "O",
            "electron_configuration": "[He]2s2 2p4",
            "isotopes": "water",
            "form": "gas",
            "category": "diatomic nonmetal",
            "source": "none",
            "wiki_link": "https://en.wikipedia.org/wiki/Oxygen",
            "compound": [{
                "Ozone": "(O3)"
            }],
            "extrainfo": {
                "History": "(Gr. oxys, sharp, acid, and genes, forming; acid former) For many centuries, workers occasionally realized air was composed of more than one component. The behavior of oxygen and nitrogen as components of air led to the advancement of the phlogiston theory of combustion, which captured the minds of chemists for a century. Oxygen was prepared by several workers, including Bayen and Borch, but they did not know how to collect it, did not study its properties, and did not recognize it as an elementary substance.Priestley is generally credited with its discovery, although Scheele also discovered it independently.Its atomic weight was used as a standard of comparison for each of the other elements until 1961 when the International Union of Pure and Applied Chemistry adopted carbon 12 as the new basis",

                "forms": "Ozone (O3), a highly active compound, is formed by the action of an electrical discharge or ultraviolet light on oxygen. =Ozone's presence in the atmosphere (amounting to the equivalent of a layer 3 mm thick under ordinary pressures and temperatures) helps prevent harmful ultraviolet rays of the sun from reaching the earth's surface. Pollutants in the atmosphere may have a detrimental effect on this ozone layer. Ozone is toxic and exposure should not exceed 0.2 mg/m# (8-hour time-weighted average - 40-hour work week).Undiluted ozone has a bluish color. Liquid ozone is bluish black and solid ozone is violet-black.",

                "compounds": "Oxygen, which is very reactive, is a component of hundreds of thousands of organic compounds and combines with most elements.",

                "Uses": "Plants and animals rely on oxygen for respiration. Hospitals frequently prescribe oxygen for patients with respiratory ailments.",

                "Costs": "The gas costs 5 cents / ft3 in small quantities, and about $15/ton in large quantities."
            }
        },
        {
            "name": "Fluorine",
            "atomic_number": "9",
            "atomic_weight": "18.998403",
            "symbol": "F",
            "electron_configuration": "[He]2s2 2p5",
            "isotopes": "none",
            "form": "gas",
            "category": "diatomic nonmetal",
            "source": "none",
            "wiki_link": "https://en.wikipedia.org/wiki/Fluorine",
            "compound": [{
                "Xenon difluoride": "XeF2",
                "Hydrogen fluoride": "HF"
            }],
            "extrainfo": {
                "History": "(L. and F. fluere, flow or flux) In 1529, Georigius Agricola described the use of fluorspar as a flux, and as early as 1670 Schwandhard found that glass was etched when exposed to fluorspar treated with acid.Scheele and many later investigators, including Davy, Gay-Lussac, Lavoisier, and Thenard,experimented with hydrofluoric acid, some experiments ending in tragedy.The element was finally isolated in 1866 by Moissan after nearly 74 years of continuous effort.",

                "Uses": "Fluorine and its compounds are used in producing uranium (from the hexafluoride) and more than 100 commercial fluorochemicals, including many well known high-temperature plastics. Hydrofluoric acid etches the glass of light bulbs, etc. Fluorochlorohydrocarbons are extensively used in air conditioning and refrigeration.The presence of fluorine as a soluble fluoride in drinking water to the extent of 2 ppm may cause mottled enamel in teeth, when used by children acquiring permanent teeth; in smaller amounts, however,fluorides are added to water supplies to prevent dental cavities.Elemental fluorine has been studied as a rocket propellant as it has an exceptionally high specific impulse value."
            }
        },
        {
            "name": "Neon",
            "atomic_number": "10",
            "atomic_weight": "20.179",
            "symbol": "Ne",
            "electron_configuration": "[He]2s2 2p6",
            "isotopes": "Natural neon is a mixture of three isotopes. Six other unstable isotopes are known.",
            "form": "gas",
            "category": "noble gas",
            "source": "none",
            "wiki_link": "https://en.wikipedia.org/wiki/Neon",
            "compound": [
                null
            ],
            "extrainfo": {}
        },
        {
            "name": "Sodium",
            "atomic_number": "11",
            "atomic_weight": "22.98977",
            "symbol": "Na",
            "electron_configuration": "[Ne]3s1",
            "isotopes": "Thirteen isotopes of sodium are recognized.",
            "form": "Solid",
            "category": "alkali metal",
            "source": "none",
            "wiki_link": "https://en.wikipedia.org/wiki/Sodium",
            "compound": [{
                "salt": "NaCl",
                "sodaash": "Na2CO3",
                "baking_soda": "NaHCO3",
                "caustic_soda": "NaOH",
                "Chile_saltpeter": "NaNO3"

            }],
            "extrainfo": {}
        },
        {
            "name": "Magnesium",
            "atomic_number": "12",
            "atomic_weight": "24.305",
            "symbol": "Mg",
            "electron_configuration": "[Ne]3s2",
            "isotopes": "none",
            "form": "Solid",
            "category": "alkaline earth metal",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Magnesium",
            "extrainfo": {}
        },
        {
            "name": "Aluminum",
            "atomic_number": "13",
            "atomic_weight": "26.98154",
            "symbol": "Al",
            "electron_configuration": "[Ne]3s2 3p1",
            "isotopes": "none",
            "form": "Solid",
            "category": "post-transition metal",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Aluminum",
            "extrainfo": {}

        },
        {
            "name": "Silicon",
            "atomic_number": "14",
            "atomic_weight": "28.086",
            "symbol": "Si",
            "electron_configuration": "[Ne]3s2 3p2",
            "isotopes": "none",
            "form": "Solid",
            "category": "metalloid",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Silicon",
            "extrainfo": {}

        },
        {
            "name": "Phosphorus",
            "atomic_number": "15",
            "atomic_weight": "30.97376",
            "symbol": "P",
            "electron_configuration": "[Ne]3s2 3p3",
            "isotopes": "none",
            "form": "Solid",
            "category": "polyatomic nonmetal",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Phosphorus",
            "extrainfo": {}

        },
        {
            "name": "Sulfur",
            "atomic_number": "16",
            "atomic_weight": "32.06",
            "symbol": "S",
            "electron_configuration": "[Ne]3s2 3p4",
            "isotopes": "none",
            "form": "Solid",
            "category": "polyatomic nonmetal",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Sulfur",
            "extrainfo": {}

        },
        {
            "name": "Chlorine",
            "atomic_number": "17",
            "atomic_weight": "35.453",
            "symbol": "Cl",
            "electron_configuration": "[Ne]3s2 3p5",
            "isotopes": "none",
            "form": "Gas",
            "category": "diatomic nonmetal",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Chlorine",
            "extrainfo": {}

        },
        {
            "name": "Argon",
            "atomic_number": "18",
            "atomic_weight": "39.948",
            "symbol": "Ar",
            "electron_configuration": "[Ne]3s2 3p6",
            "isotopes": "none",
            "form": "Gas",
            "category": "noble gas",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Argon",
            "extrainfo": {}
        },
        {
            "name": "Potassium",
            "atomic_number": "19",
            "atomic_weight": "39.948",
            "symbol": "K",
            "electron_configuration": "[Ar]4s1",
            "isotopes": "none",
            "form": "Solid",
            "category": "alkali metal",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Potassium",
            "extrainfo": {}
        },
        {
            "name": "Calcium",
            "atomic_number": "20",
            "atomic_weight": "40.08",
            "symbol": "Ca",
            "electron_configuration": "[Ar]4s2",
            "isotopes": "none",
            "form": "Solid",
            "category": "alkaline earth metal",
            "source": "none",
            "compound": [{ "Quicklime": "CaO" }],
            "wiki_link": "https://en.wikipedia.org/wiki/Calcium",
            "extrainfo": {}
        },
        {
            "name": "Scandium",
            "atomic_number": "21",
            "atomic_weight": "44.9559",
            "symbol": "Sc",
            "electron_configuration": "[Ar]4s2 3d1",
            "isotopes": "none",
            "form": "Solid",
            "category": "transition metal",
            "source": "none",
            "compound": [{}],
            "wiki_link": "https://en.wikipedia.org/wiki/Scandium",
            "extrainfo": {}
        },
        {
            "name": "Titanium",
            "atomic_number": "22",
            "atomic_weight": "47.90",
            "symbol": "Ti",
            "electron_configuration": "[Ar]4s2 3d2",
            "isotopes": "none",
            "form": "Solid",
            "category": "transition metal",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Titanium",
            "extrainfo": {}
        },
        {
            "name": "Vanadium",
            "atomic_number": "23",
            "atomic_weight": "50.9414",
            "symbol": "V",
            "electron_configuration": "[Ar]4s2 3d3",
            "isotopes": "none",
            "form": "Solid",
            "category": "transition metal",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Vanadium",
            "extrainfo": {}
        },
        {
            "name": "Chromium",
            "atomic_number": "24",
            "atomic_weight": "51.996",
            "symbol": "Cr",
            "electron_configuration": "[Ar]3d5 4s1",
            "isotopes": "none",
            "form": "Solid",
            "category": "transition metal",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Chromium",
            "extrainfo": {}
        },
        {
            "name": "Manganese",
            "atomic_number": "25",
            "atomic_weight": "54.9380",
            "symbol": "Mn",
            "electron_configuration": "[Ar]3d5 4s2",
            "isotopes": "none",
            "form": "Solid",
            "category": "transition metal",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Manganese",
            "extrainfo": {}
        },
        {
            "name": "Iron",
            "atomic_number": "26",
            "atomic_weight": "55.845",
            "symbol": "Fe",
            "electron_configuration": "[Ar]3d6 4s2",
            "isotopes": "none",
            "form": "Solid",
            "category": "transition metal",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Iron",
            "extrainfo": {}
        },
        {
            "name": "Cobalt",
            "atomic_number": "27",
            "atomic_weight": "58.9331",
            "symbol": "Co",
            "electron_configuration": "[Ar]3d7 4s2",
            "isotopes": "none",
            "form": "Solid",
            "category": "transition metal",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Cobalt",
            "extrainfo": {}
        },
        {
            "name": "Nickel",
            "atomic_number": "28",
            "atomic_weight": "58.6934",
            "symbol": "Ni",
            "electron_configuration": "[Ar]3d8 4s2",
            "isotopes": "none",
            "form": "Solid",
            "category": "transition metal",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Nickel",
            "extrainfo": {}
        },
        {
            "name": "Copper",
            "atomic_number": "29",
            "atomic_weight": "63.546",
            "symbol": "Cu",
            "electron_configuration": "[Ar]3d10 4s1",
            "isotopes": "none",
            "form": "Solid",
            "category": "transition metal",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Copper",
            "extrainfo": {}
        },
        {
            "name": "Zinc",
            "atomic_number": "30",
            "atomic_weight": "65.409",
            "symbol": "Zn",
            "electron_configuration": "[Ar]3d10 4s2",
            "isotopes": "none",
            "form": "Solid",
            "category": "transition metal",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Zinc",
            "extrainfo": {}
        },
        {
            "name": "Gallium",
            "atomic_number": "31",
            "atomic_weight": "69.723",
            "symbol": "Ga",
            "electron_configuration": "[Ar]3d10 4s2 4p1",
            "isotopes": "none",
            "form": "Solid",
            "category": "Post-transition metal",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Gallium",
            "extrainfo": {}
        },
        {
            "name": "Germanium",
            "atomic_number": "32",
            "atomic_weight": "72.64",
            "symbol": "Mn",
            "electron_configuration": "[Ar]3d10 4s2 4p2",
            "isotopes": "none",
            "form": "Solid",
            "category": "Metalloids",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Germanium",
            "extrainfo": {}
        },
        {
            "name": "Arsenic",
            "atomic_number": "33",
            "atomic_weight": "74.9216",
            "symbol": "As",
            "electron_configuration": "[Ar]3d10 4s2 4p3",
            "isotopes": "none",
            "form": "Solid",
            "category": "Metalloids",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Arsenic",
            "extrainfo": {}
        },
        {
            "name": "Selenium",
            "atomic_number": "34",
            "atomic_weight": "78.96",
            "symbol": "Se",
            "electron_configuration": "[Ar]3d10 4s2 4p4",
            "isotopes": "none",
            "form": "Solid",
            "category": "Other Non-metals",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Selenium",
            "extrainfo": {}
        },
        {
            "name": "Bromine",
            "atomic_number": "35",
            "atomic_weight": "79.904",
            "symbol": "Br",
            "electron_configuration": "[Ar]3d10 4s2 4p5",
            "isotopes": "none",
            "form": "Liquid",
            "category": "Halogens",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Bromine",
            "extrainfo": {}
        },
        {
            "name": "Krypton",
            "atomic_number": "36",
            "atomic_weight": "83.798",
            "symbol": "Kr",
            "electron_configuration": "[Ar]3d10 4s2 4p6",
            "isotopes": "none",
            "form": "Gas",
            "category": "Nobel Gases",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Krypton",
            "extrainfo": {}
        },
        {
            "name": "Rubidium",
            "atomic_number": "37",
            "atomic_weight": "85.467",
            "symbol": "Rb",
            "electron_configuration": "[kr]5s1",
            "isotopes": "none",
            "form": "Solid",
            "category": "Alkalai Metals",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Rubidium",
            "extrainfo": {}
        },
        {
            "name": "Strontium",
            "atomic_number": "38",
            "atomic_weight": "87.62",
            "symbol": "Sr",
            "electron_configuration": "[kr]5s2",
            "isotopes": "none",
            "form": "Solid",
            "category": "Alkalai Earth Metals",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Strontium",
            "extrainfo": {}
        },
        {
            "name": "Yttrium",
            "atomic_number": "39",
            "atomic_weight": "88.905",
            "symbol": "Y",
            "electron_configuration": "[kr]4d1 5s2",
            "isotopes": "none",
            "form": "Solid",
            "category": "Transition Metals",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Yttrium",
            "extrainfo": {}
        },
        {
            "name": "Zirconium",
            "atomic_number": "40",
            "atomic_weight": "91.224",
            "symbol": "Zr",
            "electron_configuration": "[kr]4d2 5s2",
            "isotopes": "none",
            "form": "Solid",
            "category": "Transition Metals",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Zirconium",
            "extrainfo": {}
        },
        {
            "name": "Niobium",
            "atomic_number": "41",
            "atomic_weight": "92.906",
            "symbol": "Nb",
            "electron_configuration": "[kr]4d4 5s1",
            "isotopes": "none",
            "form": "Solid",
            "category": "Transition Metals",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Niobium",
            "extrainfo": {}
        },
        {
            "name": "Molydenum",
            "atomic_number": "42",
            "atomic_weight": "95.94",
            "symbol": "Mo",
            "electron_configuration": "[kr]4d5 5s1",
            "isotopes": "none",
            "form": "Solid",
            "category": "Transition Metals",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Molydenum",
            "extrainfo": {}
        },
        {
            "name": "Technetium",
            "atomic_number": "43",
            "atomic_weight": "98.906",
            "symbol": "Tc",
            "electron_configuration": "[kr]4d5 5s2",
            "isotopes": "none",
            "form": "Solid",
            "category": "Transition Metals",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Technetium",
            "extrainfo": {}
        },
        {
            "name": "Ruthenium",
            "atomic_number": "44",
            "atomic_weight": "101.07",
            "symbol": "Ru",
            "electron_configuration": "[kr]4d7 5s1",
            "isotopes": "none",
            "form": "Solid",
            "category": "Transition Metals",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Ruthenium",
            "extrainfo": {}
        },
        {
            "name": "Rhodium",
            "atomic_number": "45",
            "atomic_weight": "102.905",
            "symbol": "Rh",
            "electron_configuration": "[kr]4d8 5s1",
            "isotopes": "none",
            "form": "Solid",
            "category": "Transition Metals",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Rhodium",
            "extrainfo": {}
        },
        {
            "name": "Palladium",
            "atomic_number": "46",
            "atomic_weight": "106.42",
            "symbol": "Pd",
            "electron_configuration": "[kr]4d10",
            "isotopes": "none",
            "form": "Solid",
            "category": "Transition Metals",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Palladium",
            "extrainfo": {}
        },
        {
            "name": "Silver",
            "atomic_number": "47",
            "atomic_weight": "107.868",
            "symbol": "Ag",
            "electron_configuration": "[kr]4d10 5s1",
            "isotopes": "none",
            "form": "Solid",
            "category": "Transition Metals",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Silver",
            "extrainfo": {}
        },
        {
            "name": "Cadmium",
            "atomic_number": "48",
            "atomic_weight": "112.411",
            "symbol": "Cd",
            "electron_configuration": "[kr]4d10 5s2",
            "isotopes": "none",
            "form": "Solid",
            "category": "Transition Metals",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Cadmium",
            "extrainfo": {}
        },
        {
            "name": "Indium",
            "atomic_number": "49",
            "atomic_weight": "114.818",
            "symbol": "In",
            "electron_configuration": "[kr]4d10 5s2 5p1",
            "isotopes": "none",
            "form": "Solid",
            "category": "Post-Transition Metals",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Indium",
            "extrainfo": {}
        }, {
            "name": "Tin",
            "atomic_number": "50",
            "atomic_weight": "118.710",
            "symbol": "Sn",
            "electron_configuration": "[kr]4d10 5s2 5p2",
            "isotopes": "none",
            "form": "Solid",
            "category": "Post-Transition Metals",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Tin",
            "extrainfo": {}
        },
        {
            "name": "Antimony",
            "atomic_number": "51",
            "atomic_weight": "121.760",
            "symbol": "Sb",
            "electron_configuration": "[kr]4d10 5s2 5p3",
            "isotopes": "none",
            "form": "Solid",
            "category": "Metalloids",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Antimony",
            "extrainfo": {}
        },
        {
            "name": "Tellurium",
            "atomic_number": "52",
            "atomic_weight": "127.60",
            "symbol": "Te",
            "electron_configuration": "[kr]4d10 5s2 5p4",
            "isotopes": "none",
            "form": "Solid",
            "category": "Metalloids",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Tellurium",
            "extrainfo": {}
        },
        {
            "name": "Iodine",
            "atomic_number": "53",
            "atomic_weight": "126.904",
            "symbol": "I",
            "electron_configuration": "[kr]4d10 5s2 5p5",
            "isotopes": "none",
            "form": "Solid",
            "category": "Halogens",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Iodine",
            "extrainfo": {}
        },
        {
            "name": "Xenon",
            "atomic_number": "54",
            "atomic_weight": "131.293",
            "symbol": "Xe",
            "electron_configuration": "[kr]4d10 5s2 5p6",
            "isotopes": "none",
            "form": "Gas",
            "category": "Nobel Gases",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Xenon",
            "extrainfo": {}
        },
        {
            "name": "Caesium",
            "atomic_number": "55",
            "atomic_weight": "132.905",
            "symbol": "Cs",
            "electron_configuration": "[Xe]6s1 ",
            "isotopes": "none",
            "form": "Solid",
            "category": "Alkali Metals",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Caesium",
            "extrainfo": {}
        },
        {
            "name": "Barium",
            "atomic_number": "56",
            "atomic_weight": "137.327",
            "symbol": "Ba",
            "electron_configuration": "[Xe]6s2 ",
            "isotopes": "none",
            "form": "Solid",
            "category": "alkaline earth metal",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Barium",
            "extrainfo": {}
        },
        {
            "name": "Lanthanum",
            "atomic_number": "57",
            "atomic_weight": "138.905",
            "symbol": "La",
            "electron_configuration": "[Xe]5d1 6s2 ",
            "isotopes": "none",
            "form": "Solid",
            "category": "Lanthanoids",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Lanthanum",
            "extrainfo": {}
        },
        {
            "name": "Cerium",
            "atomic_number": "58",
            "atomic_weight": "140.116",
            "symbol": "Ce",
            "electron_configuration": "[Xe]4f1 5d1 6s2 ",
            "isotopes": "none",
            "form": "Solid",
            "category": "Lanthanoids",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Cerium",
            "extrainfo": {}
        },
        {
            "name": "Praseodymium",
            "atomic_number": "59",
            "atomic_weight": "140.904",
            "symbol": "Pr",
            "electron_configuration": "[Xe]4f3 6s2 ",
            "isotopes": "none",
            "form": "Solid",
            "category": "Lanthanoids",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Praseodymium",
            "extrainfo": {}
        },
        {
            "name": "Neodymium",
            "atomic_number": "60",
            "atomic_weight": "144.242",
            "symbol": "Nd",
            "electron_configuration": "[Xe]4f4 6s2 ",
            "isotopes": "none",
            "form": "Solid",
            "category": "Lanthanoids",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Neodymium",
            "extrainfo": {}
        },
        {
            "name": "Promethium",
            "atomic_number": "61",
            "atomic_weight": "146.915",
            "symbol": "Pm",
            "electron_configuration": "[Xe]4f5 6s2 ",
            "isotopes": "none",
            "form": "Solid",
            "category": "Lanthanoids",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Promethium",
            "extrainfo": {}
        },
        {
            "name": "Samarium",
            "atomic_number": "62",
            "atomic_weight": "150.36",
            "symbol": "Sm",
            "electron_configuration": "[Xe]4f6 6s2 ",
            "isotopes": "none",
            "form": "Solid",
            "category": "Lanthanoids",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Samarium",
            "extrainfo": {}
        },
        {
            "name": "Europium",
            "atomic_number": "63",
            "atomic_weight": "151.964",
            "symbol": "Eu",
            "electron_configuration": "[Xe]4f7 6s2 ",
            "isotopes": "none",
            "form": "Solid",
            "category": "Lanthanoids",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Europium",
            "extrainfo": {}
        },
        {
            "name": "Gadolinium",
            "atomic_number": "64",
            "atomic_weight": "157.25",
            "symbol": "Gd",
            "electron_configuration": "[Xe]4f7 5d1 6s2 ",
            "isotopes": "none",
            "form": "Solid",
            "category": "Lanthanoids",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Gadolinium",
            "extrainfo": {}
        },
        {
            "name": "Terbium",
            "atomic_number": "65",
            "atomic_weight": "158.925",
            "symbol": "Tb",
            "electron_configuration": "[Xe]4f9 6s2 ",
            "isotopes": "none",
            "form": "Solid",
            "category": "Lanthanoids",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Terbium",
            "extrainfo": {}
        },
        {
            "name": "Dysprosium",
            "atomic_number": "66",
            "atomic_weight": "162.500",
            "symbol": "Dy",
            "electron_configuration": "[Xe]4f10 6s2 ",
            "isotopes": "none",
            "form": "Solid",
            "category": "Lanthanoids",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Dysprosium",
            "extrainfo": {}
        },
        {
            "name": "Holmium",
            "atomic_number": "67",
            "atomic_weight": "164.93",
            "symbol": "Ho",
            "electron_configuration": "[Xe]4f11 6s2 ",
            "isotopes": "none",
            "form": "Solid",
            "category": "Lanthanoids",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Holmium",
            "extrainfo": {}
        },
        {
            "name": "Erbium",
            "atomic_number": "68",
            "atomic_weight": "167.259",
            "symbol": "Er",
            "electron_configuration": "[Xe]4f12 6s2 ",
            "isotopes": "none",
            "form": "Solid",
            "category": "Lanthanoids",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Erbium",
            "extrainfo": {}
        },
        {
            "name": "Thulium",
            "atomic_number": "69",
            "atomic_weight": "168.934",
            "symbol": "Tm",
            "electron_configuration": "[Xe]4f13 6s2 ",
            "isotopes": "none",
            "form": "Solid",
            "category": "Lanthanoids",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Thulium",
            "extrainfo": {}
        },
        {
            "name": "Ytterbium",
            "atomic_number": "70",
            "atomic_weight": "173.04",
            "symbol": "Yb",
            "electron_configuration": "[Xe]4f14 6s2 ",
            "isotopes": "none",
            "form": "Solid",
            "category": "Lanthanoids",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Ytterbium",
            "extrainfo": {}
        },
        {
            "name": "Lutetium",
            "atomic_number": "71",
            "atomic_weight": "174.967",
            "symbol": "Lu",
            "electron_configuration": "[Xe]4f14 5d1 6s2 ",
            "isotopes": "none",
            "form": "Solid",
            "category": "Lanthanoids",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Lutetium",
            "extrainfo": {}
        },
        {
            "name": "Hafnium",
            "atomic_number": "72",
            "atomic_weight": "178.49",
            "symbol": "Hf",
            "electron_configuration": "[Xe]4f14 5d2 6s2 ",
            "isotopes": "none",
            "form": "Solid",
            "category": "Transition Metals",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Hafnium",
            "extrainfo": {}
        },
        {
            "name": "Tantalum",
            "atomic_number": "73",
            "atomic_weight": "180.947",
            "symbol": "Ta",
            "electron_configuration": "[Xe]4f14 5d3 6s2 ",
            "isotopes": "none",
            "form": "Solid",
            "category": "Transition Metals",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Tantalum",
            "extrainfo": {}
        },
        {
            "name": "Tungsten",
            "atomic_number": "74",
            "atomic_weight": "183.84",
            "symbol": "W",
            "electron_configuration": "[Xe]4f14 5d4 6s2 ",
            "isotopes": "none",
            "form": "Solid",
            "category": "Transition Metals",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Tungsten",
            "extrainfo": {}
        },
        {
            "name": "Rhenium",
            "atomic_number": "75",
            "atomic_weight": "186.207",
            "symbol": "Re",
            "electron_configuration": "[Xe]4f14 5d5 6s2 ",
            "isotopes": "none",
            "form": "Solid",
            "category": "Transition Metals",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Rhenium",
            "extrainfo": {}
        },
        {
            "name": "Osmium",
            "atomic_number": "76",
            "atomic_weight": "190.23",
            "symbol": "Os",
            "electron_configuration": "[Xe]4f14 5d6 6s2 ",
            "isotopes": "none",
            "form": "Solid",
            "category": "Transition Metals",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Osmium",
            "extrainfo": {}
        },
        {
            "name": "Iridium",
            "atomic_number": "77",
            "atomic_weight": "192.217",
            "symbol": "Ir",
            "electron_configuration": "[Xe]4f14 5d7 6s2 ",
            "isotopes": "none",
            "form": "Solid",
            "category": "Transition Metals",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Iridium",
            "extrainfo": {}
        },
        {
            "name": "Platinum",
            "atomic_number": "78",
            "atomic_weight": "195.084",
            "symbol": "Pt",
            "electron_configuration": "[Xe]4f14 5d9 6s1 ",
            "isotopes": "none",
            "form": "Solid",
            "category": "Transition Metals",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Platinum",
            "extrainfo": {}
        },
        {
            "name": "Glod",
            "atomic_number": "79",
            "atomic_weight": "196.966",
            "symbol": "Au",
            "electron_configuration": "[Xe]4f14 5d10 6s1 ",
            "isotopes": "none",
            "form": "Solid",
            "category": "Transition Metals",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Gold",
            "extrainfo": {}
        },
        {
            "name": "Mercury",
            "atomic_number": "80",
            "atomic_weight": "200.59",
            "symbol": "Hg",
            "electron_configuration": "[Xe]4f14 5d10 6s2 ",
            "isotopes": "none",
            "form": "Solid",
            "category": "Transition Metals",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Mercury",
            "extrainfo": {}
        },
        {
            "name": "Thallium",
            "atomic_number": "81",
            "atomic_weight": "204.383",
            "symbol": "Tl",
            "electron_configuration": "[Xe]4f14 5d10 6s2 6p1 ",
            "isotopes": "none",
            "form": "Solid",
            "category": "Post-Transition Metals",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Thallium",
            "extrainfo": {}
        },
        {
            "name": "Lead",
            "atomic_number": "82",
            "atomic_weight": "207.2",
            "symbol": "Pb",
            "electron_configuration": "[Xe]4f14 5d10 6s2 6p2 ",
            "isotopes": "none",
            "form": "Solid",
            "category": "Post-Transition Metals",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Lead",
            "extrainfo": {}
        },
        {
            "name": "Bismuth",
            "atomic_number": "83",
            "atomic_weight": "208.9804",
            "symbol": "Bi",
            "electron_configuration": "[Xe]4f14 5d10 6s2 6p3 ",
            "isotopes": "none",
            "form": "Solid",
            "category": "Post-Transition Metals",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Bismuth",
            "extrainfo": {}
        },
        {
            "name": "Polonium",
            "atomic_number": "84",
            "atomic_weight": "208.9824",
            "symbol": "Po",
            "electron_configuration": "[Xe]4f14 5d10 6s2 6p4 ",
            "isotopes": "none",
            "form": "Solid",
            "category": "Metalloids",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Polonium",
            "extrainfo": {}
        },
        {
            "name": "Astatine",
            "atomic_number": "85",
            "atomic_weight": "209.9871",
            "symbol": "At",
            "electron_configuration": "[Xe]4f14 5d10 6s2 6p5 ",
            "isotopes": "none",
            "form": "Solid",
            "category": "Halogens",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Astatine",
            "extrainfo": {}
        },
        {
            "name": "Randon",
            "atomic_number": "86",
            "atomic_weight": "222.0176",
            "symbol": "Rn",
            "electron_configuration": "[Xe]4f14 5d10 6s2 6p6 ",
            "isotopes": "none",
            "form": "Gas",
            "category": "Noble Gases",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Randon",
            "extrainfo": {}
        },
        {
            "name": "Francium",
            "atomic_number": "87",
            "atomic_weight": "223.0197",
            "symbol": "Fr",
            "electron_configuration": "[Rn]7s1 ",
            "isotopes": "none",
            "form": "Solid",
            "category": "Alkali Metals",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Francium",
            "extrainfo": {}
        },
        {
            "name": "Radium",
            "atomic_number": "88",
            "atomic_weight": "226.0254",
            "symbol": "Ra",
            "electron_configuration": "[Rn]7s2 ",
            "isotopes": "none",
            "form": "Solid",
            "category": "Alkaline earth metals",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Radium",
            "extrainfo": {}
        },
        {
            "name": "Actinium",
            "atomic_number": "89",
            "atomic_weight": "227.0278",
            "symbol": "Ac",
            "electron_configuration": "[Rn]6d1 7s2 ",
            "isotopes": "none",
            "form": "Solid",
            "category": "Actinoids",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Actinium",
            "extrainfo": {}
        },
        {
            "name": "Thorium",
            "atomic_number": "90",
            "atomic_weight": "232.0380",
            "symbol": "Th",
            "electron_configuration": "[Rn]6d2 7s2 ",
            "isotopes": "none",
            "form": "Solid",
            "category": "Actionids",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Thorium",
            "extrainfo": {}
        },
        {
            "name": "Protactinium",
            "atomic_number": "91",
            "atomic_weight": "231.0358",
            "symbol": "Pa",
            "electron_configuration": "[Rn]5f2 6d1 7s2 ",
            "isotopes": "none",
            "form": "Solid",
            "category": "Actionids",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Protactinium",
            "extrainfo": {}
        },
        {
            "name": "Uranium",
            "atomic_number": "92",
            "atomic_weight": "238.0289",
            "symbol": "U",
            "electron_configuration": "[Rn]5f3 6d1 7s2 ",
            "isotopes": "none",
            "form": "Solid",
            "category": "Actionids",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Uranium",
            "extrainfo": {}
        },
        {
            "name": "Neptunium",
            "atomic_number": "93",
            "atomic_weight": "237.0482",
            "symbol": "Np",
            "electron_configuration": "[Rn]5f4 6d1 7s2 ",
            "isotopes": "none",
            "form": "Solid",
            "category": "Actionids",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Neptunium",
            "extrainfo": {}
        },
        {
            "name": "Plutonium",
            "atomic_number": "94",
            "atomic_weight": "244.0642",
            "symbol": "Pu",
            "electron_configuration": "[Rn]5f6 7s2 ",
            "isotopes": "none",
            "form": "Solid",
            "category": "Actionids",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Plutonium",
            "extrainfo": {}
        },
        {
            "name": "Americium",
            "atomic_number": "95",
            "atomic_weight": "243.0614",
            "symbol": "Am",
            "electron_configuration": "[Rn]5f7 7s2 ",
            "isotopes": "none",
            "form": "Solid",
            "category": "Actionids",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Americium",
            "extrainfo": {}
        },
        {
            "name": "Curium",
            "atomic_number": "96",
            "atomic_weight": "247.0703",
            "symbol": "Cm",
            "electron_configuration": "[Rn]5f7 6d1 7s2 ",
            "isotopes": "none",
            "form": "Solid",
            "category": "Actionids",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Curium",
            "extrainfo": {}
        },
        {
            "name": "Berkelium",
            "atomic_number": "97",
            "atomic_weight": "247.0703",
            "symbol": "Bk",
            "electron_configuration": "[Rn]5f9 7s2 ",
            "isotopes": "none",
            "form": "Solid",
            "category": "Actionids",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Berkelium",
            "extrainfo": {}
        },
        {
            "name": "Californium",
            "atomic_number": "98",
            "atomic_weight": "251.0796",
            "symbol": "Cf",
            "electron_configuration": "[Rn]5f10 7s2 ",
            "isotopes": "none",
            "form": "Solid",
            "category": "Actionids",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Californium",
            "extrainfo": {}
        },
        {
            "name": "Einsteinium",
            "atomic_number": "99",
            "atomic_weight": "252.0829",
            "symbol": "Es",
            "electron_configuration": "[Rn]5f11 7s2 ",
            "isotopes": "none",
            "form": "Solid",
            "category": "Actionids",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Einsteinium",
            "extrainfo": {}
        },
        {
            "name": "Fermium",
            "atomic_number": "100",
            "atomic_weight": "257.0951",
            "symbol": "Fm",
            "electron_configuration": "[Rn]5f12 7s2 ",
            "isotopes": "none",
            "form": "Solid",
            "category": "Actionids",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Fermium",
            "extrainfo": {}
        },
        {
            "name": "Mendeleveium",
            "atomic_number": "101",
            "atomic_weight": "258.0951",
            "symbol": "Md",
            "electron_configuration": "[Rn]5f13 7s2 ",
            "isotopes": "none",
            "form": "Solid",
            "category": "Actionids",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Mendeleveium",
            "extrainfo": {}
        },
        {
            "name": "Nobelium",
            "atomic_number": "102",
            "atomic_weight": "259.1009",
            "symbol": "No",
            "electron_configuration": "[Rn]5f14 7s2 ",
            "isotopes": "none",
            "form": "Solid",
            "category": "Actionids",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Nobelium",
            "extrainfo": {}
        },
        {
            "name": "Lawrencium",
            "atomic_number": "103",
            "atomic_weight": "266.1193",
            "symbol": "Lr",
            "electron_configuration": "[Rn]5f14 7s2 7p1 ",
            "isotopes": "none",
            "form": "Solid",
            "category": "Actionids",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Lawrencium",
            "extrainfo": {}
        },
        {
            "name": "Rutherfordium",
            "atomic_number": "104",
            "atomic_weight": "261",
            "symbol": "Rf",
            "electron_configuration": "[Rn]5f14 6d2 7p2 ",
            "isotopes": "none",
            "form": "Solid",
            "category": "Transition Metals",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Rutherfordium",
            "extrainfo": {}
        },
        {
            "name": "Dubnium",
            "atomic_number": "105",
            "atomic_weight": "262",
            "symbol": "Db",
            "electron_configuration": "[Rn]5f14 6d3 7s2 ",
            "isotopes": "none",
            "form": "Solid",
            "category": "Transition Metals",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Dubnium",
            "extrainfo": {}
        },
        {
            "name": "Seaborgium",
            "atomic_number": "106",
            "atomic_weight": "262",
            "symbol": "Sg",
            "electron_configuration": "[Rn]5f14 6d4 7s2 ",
            "isotopes": "none",
            "form": "Solid",
            "category": "Transition Metals",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Seaborgium",
            "extrainfo": {}
        },
        {
            "name": "Bohrium",
            "atomic_number": "107",
            "atomic_weight": "264",
            "symbol": "Bh",
            "electron_configuration": "[Rn]5f14 6d5 7s2 ",
            "isotopes": "none",
            "form": "Solid",
            "category": "Transition Metals",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Bohrium",
            "extrainfo": {}
        },
        {
            "name": "Hassium",
            "atomic_number": "108",
            "atomic_weight": "269",
            "symbol": "Hs",
            "electron_configuration": "[Rn]5f14 6d6 7s2 ",
            "isotopes": "none",
            "form": "Solid",
            "category": "Transition Metals",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Hassium",
            "extrainfo": {}
        },
        {
            "name": "Meitnerium",
            "atomic_number": "109",
            "atomic_weight": "268",
            "symbol": "Mt",
            "electron_configuration": "[Rn]5f14 6d7 7s2 ",
            "isotopes": "none",
            "form": "Solid",
            "category": "Transition Metals",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Meitnerium",
            "extrainfo": {}
        },
        {
            "name": "Darmstadium",
            "atomic_number": "110",
            "atomic_weight": "281.1620",
            "symbol": "Ds",
            "electron_configuration": "[Rn]5f14 6d8 7s2 ",
            "isotopes": "none",
            "form": "Solid",
            "category": "Transition Metals",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Darmstadium",
            "extrainfo": {}
        },
        {
            "name": "Roentgenium",
            "atomic_number": "111",
            "atomic_weight": "281.1684",
            "symbol": "Rg",
            "electron_configuration": "[Rn]5f14 6d9 7s2 ",
            "isotopes": "none",
            "form": "Solid",
            "category": "Transition Metals",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Roentgenium",
            "extrainfo": {}
        },
        {
            "name": "Copernicium",
            "atomic_number": "112",
            "atomic_weight": "285.1744",
            "symbol": "Cn",
            "electron_configuration": "[Rn]5f14 6d10 7s2 ",
            "isotopes": "none",
            "form": "Solid",
            "category": "Transition Metals",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Copernicium",
            "extrainfo": {}
        },
        {
            "name": "Nihonium",
            "atomic_number": "113",
            "atomic_weight": "286.1810",
            "symbol": "Nh",
            "electron_configuration": "[Rn]5f14 6d10 7s2 7p1 ",
            "isotopes": "none",
            "form": "Solid",
            "category": "Post-Transition Metals",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Nihonium",
            "extrainfo": {}
        },
        {
            "name": "Flerovium",
            "atomic_number": "114",
            "atomic_weight": "287.1904",
            "symbol": "Fl",
            "electron_configuration": "[Rn]5f14 6d10 7s2 7p2 ",
            "isotopes": "none",
            "form": "Solid",
            "category": "Post-Transition Metals",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Flerovium",
            "extrainfo": {}
        },
        {
            "name": "Moscovium",
            "atomic_number": "115",
            "atomic_weight": "288.1943",
            "symbol": "Mc",
            "electron_configuration": "[Rn]5f14 6d10 7s2 7p3 ",
            "isotopes": "none",
            "form": "Solid",
            "category": "Post-Transition Metals",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Moscovium",
            "extrainfo": {}
        },
        {
            "name": "Livermorium",
            "atomic_number": "116",
            "atomic_weight": "291.2045",
            "symbol": "Lv",
            "electron_configuration": "[Rn]5f14 6d10 7s2 7p4 ",
            "isotopes": "none",
            "form": "Solid",
            "category": "Post-Transition Metals",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Livermorium",
            "extrainfo": {}
        },
        {
            "name": "Tennessine",
            "atomic_number": "117",
            "atomic_weight": "294.2104",
            "symbol": "Ts",
            "electron_configuration": "[Rn]5f14 6d10 7s2 7p5 ",
            "isotopes": "none",
            "form": "Solid",
            "category": "Halogens",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Tennessine",
            "extrainfo": {}
        },
        {
            "name": "Oganesson",
            "atomic_number": "118",
            "atomic_weight": "294.2139",
            "symbol": "Og",
            "electron_configuration": "[Rn]5f14 6d10 7s2 7p6 ",
            "isotopes": "none",
            "form": "Solid",
            "category": "Noble Gases",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Oganesson",
            "extrainfo": {}
        },
        {
            "name": "Ununennium",
            "atomic_number": "119",
            "atomic_weight": "316",
            "symbol": "Uue",
            "electron_configuration": "[Og]8s1 ",
            "isotopes": "none",
            "form": "Liquid",
            "category": "Alkali Metals",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Ununennium",
            "extrainfo": {}
        },
        {
            "name": "Unbinilium",
            "atomic_number": "120",
            "atomic_weight": "320",
            "symbol": "Ubn",
            "electron_configuration": "[Og]8s2 ",
            "isotopes": "none",
            "form": "none",
            "category": "Alkaline Earth Metals",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Unbinilium",
            "extrainfo": {}
        },
        {
            "name": "Unbiunium",
            "atomic_number": "121",
            "atomic_weight": "320",
            "symbol": "Ubu",
            "electron_configuration": "[Og]8s2 5g1 ",
            "isotopes": "none",
            "form": "none",
            "category": "Superactinoid",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Unbiunium",
            "extrainfo": {}
        },
        {
            "name": "Unbibium",
            "atomic_number": "122",
            "atomic_weight": "321",
            "symbol": "Ubb",
            "electron_configuration": "[Og]8s2 6f1 7d1  ",
            "isotopes": "none",
            "form": "none",
            "category": "Superactinoid",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Unbibium",
            "extrainfo": {}
        },
        {
            "name": "Unbitrium",
            "atomic_number": "123",
            "atomic_weight": "325",
            "symbol": "Ubt",
            "electron_configuration": "[Og]8s2 6f1 7d1 5g1",
            "isotopes": "none",
            "form": "none",
            "category": "Superactinoid",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Unbitrium",
            "extrainfo": {}
        },
        {
            "name": "Unbiquadium",
            "atomic_number": "124",
            "atomic_weight": "330",
            "symbol": "Ubq",
            "electron_configuration": "[Og]8s2 6f3 8p1",
            "isotopes": "none",
            "form": "none",
            "category": "Superactinoid",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Unbiquadium",
            "extrainfo": {}
        },
        {
            "name": "Unbipentium",
            "atomic_number": "125",
            "atomic_weight": "332",
            "symbol": "Ubp",
            "electron_configuration": "[Og]8s2 8p1 6f3 5g1 ",
            "isotopes": "none",
            "form": "none",
            "category": "Superactinoid",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Unbipentium",
            "extrainfo": {}
        },
        {
            "name": "Unbihexium",
            "atomic_number": "126",
            "atomic_weight": "334",
            "symbol": "Ubh",
            "electron_configuration": "[Og]8s2 8p1 7d1 6f2 5g2 ",
            "isotopes": "none",
            "form": "none",
            "category": "Superactinoid",
            "source": "none",
            "compound": [null],
            "wiki_link": "https://en.wikipedia.org/wiki/Unbihexium",
            "extrainfo": {}
        }

    ]
};

function setData(symbol) {
    $.each(json["Elements"], function(index, value) {
        if (value["symbol"] == symbol) {
            var dataHtml = ("<p id='name'>Name:" + value["name"] + "</p>" + "<p id='atn'>AtomicNumber:" + value["atomic_number"] + "</p>" + "<p id='symbol'>Symbol:" + value["symbol"] + "</p>")
            var btn = ("<button class='btn' style='width:78px;font-size:10px'>ShowReaction</button>" + "<a href='#' class='Modal'>moreInfo");
            $('.popup').html(dataHtml + btn)

            //$('.extrainfo').html("<p>"+value["extrainfo"]["History"]+"</p>")
            return false;
        }
    });

}

function showExtraInfoPopup(object, symbol) {
    $.each(json["Elements"], function(index, value) {
        if (value["symbol"] == symbol) {

            // set ui data for extra info using value parameter

            $('.BoxModal').append("<p>Name: " + value["name"] + "</p>")
            $('.BoxModal').append("<p>Atomic_Weight: " + value["atomic_weight"] + "</p>")
            $('.BoxModal').append("<p>Electronic_Confrguration: " + value["electron_configuration"] + "</p>")
            $('.BoxModal').append("<p>Category: " + value["category"] + "</p>")
            $('.BoxModal').append("<p>click<a href='" + value["wiki_link"] + "'target='_blank'>Here</a></p>")
                // <a href='https://www.google.com'>Google</a>
        } else {
            $(".BoxModal").click(".close", function() {
                $("p").remove();
            })
        }

    });
    var offset = object.offset();
    $('.BoxModal')
        .fadeIn()
        .css({
            left: Math.min(offset.left, $(window).innerWidth() - $('.BoxModal').outerWidth()),
            top: offset.top + object.innerHeight(),
            positin: fixed

        });

}